config/routes.rb
TtgtAws::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :instances, only: [:new, :create, :destroy, :start, :stop]

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  get 'instances/start/:id' => 'instances#start', :as => :start_instances
  get 'instances/stop/:id' => 'instances#stop', :as => :stop_instances

  get 'users/unlock/:id' => 'users#unlock', :as => :unlock
  
  
  

end

app/models/instance.rb
class Instance < ActiveRecord::Base

  # IMAGES = [Amazon2013.03.1, RHEL6.5, SUSEServer11, UbuntuServer14.04] 
  IMAGES = ['ami-fb8e9292', 'ami-8d756fe4', 'ami-e8084981', 'ami-018c9568']
  TYPES = ['t1.micro', 'm1.small', 'm3.medium', 'm3.large', 'm3.xlarge', 'm3.2xlarge']
  KEYS = ['TT-AWS-ENG-201405', 'test-key-pair-elg-01', 'tjguthrie4600']
  
  attr_accessible :name, :image, :instanceType, :instanceID, :ip, :sshKeys

  belongs_to :user

  VAILD_IMAGE_REGEX = /^ami-/i
  VAILD_ID_REGEX = /^i-/i

  validates :image, presence: true, format: { with: VAILD_IMAGE_REGEX }
  validates :instanceType, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :instanceID, format: { with: VAILD_ID_REGEX }
  validates :sshKeys, presence: true

  default_scope order: 'instances.created_at DESC'
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController

  require 'Cloud'
  before_filter :signed_in_user

  # New form for the instance to be created
  def new
    @instance = Instance.new
  end

  # Creates instance in AWS and in application database
  def create    

    # Find the user
    current_user ||= User.find_by_remember_token(cookies[:remember_token])
      
    # Get information from form
    image = params[:instance][:image]
    instanceType = params[:instance][:instanceType]
    sshKeys = params[:instance][:sshKeys]

    # Update weights
    success = updateWeight(current_user, instanceType, "add")

    if success
      # Create the new instance in AWS
      cloud = Cloud.new("/apps/local/ttgt-aws/conf/AWS.conf")
      cloudInstance = cloud.createInstance(image, instanceType, sshKeys)
      cloudID = cloudInstance.id
      cloudIP = nil
      
      # Wait for amazon to assign the ip address to the instance
      while cloudIP.nil?
        cloudIP = cloudInstance.ip_address
        sleep(1)
      end
    
      # Save the instance information in the database
      @instance = current_user.instances.build(params[:instance].merge(:instanceID => cloudID, :ip => cloudIP))
      if @instance.save
        flash[:success] = "Instance Created!"
        redirect_to "/users/#{current_user.id}"
      else
        render 'new'
      end
    end
  end

  def destroy
    # Find the user and insatnce
    current_user ||= User.find_by_remember_token(cookies[:remember_token])
    instance = Instance.find(params[:id])
    instanceType = instance.instanceType

    # Update weights
    updateWeight(current_user, instanceType, "subtract")

    # Destroy the instance in AWS
    cloud = Cloud.new("/apps/local/ttgt-aws/conf/AWS.conf")
    awsID = instance.instanceID
    cloud.terminateInstance(awsID)

    # Destroy the instance in the database
    instance.destroy
    session[:return_to] ||= request.referer
    flash[:success] = "Instance destroyed."
    redirect_to session.delete(:return_to)
  end

  def start
    # Get the user and instance
    instance = Instance.find(params[:id])
    current_user ||= User.find_by_remember_token(cookies[:remember_token])

    # Start the instance in the cloud
    cloud = Cloud.new("/apps/local/ttgt-aws/conf/AWS.conf")
    awsID = instance.instanceID
    cloud.startInstance(awsID)

    # Report back to user
    session[:return_to] ||= request.referer
    flash[:success] = "Instance Starting!"
    redirect_to session.delete(:return_to)
  end

  def stop
    # Get the user and instance
    instance = Instance.find(params[:id])
    current_user ||= User.find_by_remember_token(cookies[:remember_token])

    # Stop the instance in the cloud
    cloud = Cloud.new("/apps/local/ttgt-aws/conf/AWS.conf")
    awsID = instance.instanceID
    cloud.stopInstance(awsID)
    
    # Report back to user
    session[:return_to] ||= request.referer
    flash[:success] = "Instance Stopping!"
    redirect_to session.delete(:return_to)
  end

  private

  # Takes in the user and type of the instance added or subtracted  and updates the weight
  def updateWeight(user, type, function)

    success = false

    weightMapping = {'t1.micro' => 1, 'm1.small' => 2, 'm3.medium' => 4, 'm3.large' => 6, 'm3.xlarge' => 12, 'm3.2xlarge' => 24}
    currentPoints = user.weightPoints
    if function == "add"
      newPoints = currentPoints + weightMapping[type]
    else
      newPoints = currentPoints - weightMapping[type]
    end

    if newPoints < 25
      user.update_column(:weightPoints, newPoints)
      success = true
    else
      flash[:failure] = "Maximum points exceeded, destroy some instances"
      redirect_to "/users/#{current_user.id}"
      success = false
    end
    return success
  end

end

app/helpers/instance_helper.rb
module InstanceHelper

require 'Cloud'


  def getStat(id)
    cloud = Cloud.new("/apps/local/ttgt-aws/conf/AWS.conf")
    cloudStatus = cloud.getStatus(id).to_s
    value = 0

    if cloudStatus == "running"
      value = 1
    elsif cloudStatus == "pending" || cloudStatus == "shutting-down" || cloudStatus == "stopping"
      value = 2
    else
      value = 3
    end

    return value
  end

end

app/views/instances/_error_messages.html.erb
<% if @instance.errors.any? %>
<div id="error_explaination">
  <div class="alert alert-error">
    The form contains <%= pluralize(@instance.errors.count, "error") %>.
  </div>
  <ul>
    <% @instance.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/instances/_instance.html.erb
<head><meta http-equiv="refresh" content="20"></head>
<li>
  <span class="name"> <%= instance.name %> </span>
  <span class="info"> 
    ID: <%= instance.instanceID %>
      <%= link_to "start", start_instances_path(instance)  %> 
  </span>
  <br>
  <span class="info">
    IP: <%= instance.ip %> 
      <%= link_to "stop", stop_instances_path(instance) %> 
  </span>
  <br>
  <span class="info"> 
    Type: <%= instance.instanceType %> 
        <%= link_to "delete", instance , method: :delete, confirm: "You sure?" %> 
  </span>
  <br>
  <span class="info"> 
    Image: <%= instance.image %></span>
  <br>

  <% status = getStat(instance.instanceID) %>
  <% if status == 1 %>
    <span class="info"> Status:   <%= image_tag("green.png", alt: "TTGT" ) %></span>
  <% elsif status == 2 %>
    <span class="info"> Status: WAIT FOR GREEN/RED!!!   <%= image_tag("yellow.png", alt: "TTGT" ) %></span>
  <% else status == 3 %>
      <span class="info"> Status:   <%= image_tag("red.png", alt: "TTGT" ) %></span>
  <% end %>
</li>

app/views/instances/new.html.erb
<% provide(:title, 'Instance creation') %>
<h1>Create instance</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@instance) do |f| %>
      <%= render 'instances/error_messages' %>
    
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :image %>
      <%= f.select :image, Instance::IMAGES %>

      <%= f.label :instanceType %>
      <%= f.select :instanceType, Instance::TYPES %>

      <%= f.label :sshKeys %>
      <%= f.select :sshKeys, Instance::KEYS %>

      <%= f.submit "Create my instance", class: "btn btn-large btn=primary" %>
    <% end %>
  </div>
</div>