config/routes.rb
TtgtAws::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :instances, only: [:new, :create, :destroy, :start, :stop]

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  get 'instances/start/:id' => 'instances#start', :as => :start_instances
  get 'instances/stop/:id' => 'instances#stop', :as => :stop_instances

  get 'users/unlock/:id' => 'users#unlock', :as => :unlock
  
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :weightPoints, :lock
  has_secure_password

  has_many :instances, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VAILD_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VAILD_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  validates :weightPoints, length: { maximum: 25 }
  validates :lock, presence: true

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  require 'net/smtp'

  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: :destroy

  # Shows a single user record
  def show
    @user = User.find(params[:id])
    @instances = @user.instances
  end

  # Form for new user record
  def new
    @user = User.new
  end

  # Create the new user record, provided from information in the form
  def create
    @user = User.new(params[:user].merge(:weightPoints => 0, :lock => true))
    if @user.save
      # Handle a successful save
      sendEmail @user
      flash[:success] = "Welcome to the AWS Web Interface! Your system administrator must manually unlock your account. A request has been sent. You will get an email when your account has been activated."
      redirect_to @user
    else
      render 'new'
    end
  end

  # Display form for existing record
  def edit
  end

  # Update a single record from form in edit
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      # Handle sucessful update
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  # Query and list all users
  def index
    @users = User.all
  end

  # Remove a user from the database
  def destroy
    user = User.find(params[:id])
    destroyInstances(user)
    user.destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  # If the account is locked this function will unlock the user
  def unlock
    user = User.find(params[:id])
    if user.lock
      user.toggle!(:lock)
    end
    session[:return_to] ||= request.referer
    flash[:success] = "#{user.name}'s account has been unlocked!"
    redirect_to session.delete(:return_to)
  end

  private

    # Is the user signed in, if not redirect them
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in."
      end
    end

    # Authorization
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    # Authoriztion for super user
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

    # Destroys all instances assicoated with user in AWS
    def destroyInstances(user)
      cloud = Cloud.new("/apps/local/ttgt-aws/conf/AWS.conf")
      instances = Instance.where(:user_id => user.id)
      for instance in instances
        awsID = instance.instanceID
        cloud.terminateInstance(awsID)
      end
    end

# Sends email to sysadmins for new account activation
def sendEmail(user)
  name = user.name
  email = user.email
  id = user.id
  message = <<MESSAGE_END
From: AWS Application <aws@railsma1.techtarget.com>
To: SysAdmins <sysadmins@techtarget.com>
Subject: Account Request

\nName = #{name} \nEmail = #{email} \nID = #{id} \n
MESSAGE_END
  Net::SMTP.start('localhost') do |smtp|
    smtp.send_message message, 'aws@railsma1.techtarget.com',
    'sysadmins@techtarget.com'
  end
end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://s.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explaination">
  <div class="alert alert-error">
    The form contains <%= pluralize(@user.errors.count, "error") %>.
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'users/error_messages' %>
      
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>
      
      <%= f.label :password %>
      <%= f.password_field :password %>
      
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
      
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails"> change </a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 52 %>
      <%= link_to user.name, user %>
      <span class="info">
        <% if current_user.admin? && !current_user?(user) %>
          <%= link_to "delete", user, method: :delete, confirm: "You sure?" %>
        <% end %>
      </span>
      <br>
      <font size="2"> Points: <%= user.weightPoints %> </font>
      <span class="info">
        <% if current_user.admin? && !current_user?(user) && user.lock %>
          <%= link_to "unlock", unlock_path(user) %>
        <% end %>
      </span>
    </li>
 <% end %> 
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'users/error_messages' %>
    
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    
    <%= f.submit "Create my account", class: "btn btn-large btn=primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
	<%= gravatar_for @user %>
	<%= @user.name %>
	<br>
	<font size="2"> Points: <%= @user.weightPoints %> </font>
	<% user=@user %>
	
	<% if current_user?(user) %>
	  <div id="actions">
	    <%= link_to "Create Instance", new_instance_path, class: "btn btn-large btn-primary" %>
	  </div>
	<% end %>	
	</section>
      </h1>
    </section>
  </aside>
  <div class="span8">
    <% if @user.instances.any? && (current_user?(user) || (current_user && current_user.admin?)) %>
      <h3>Instances (<%= @user.instances.count %>)</h3>
      <ol class="instances">
	<%= render @instances %>
      </ol>
    <% end %>
    </div>
</div>